//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Role
{

public sealed partial class RoleData :  Bright.Config.BeanBase 
{
    public RoleData(ByteBuf _buf) 
    {
        Code = _buf.ReadInt();
        Level = _buf.ReadInt();
        Hp = _buf.ReadInt();
        BasePower = _buf.ReadInt();
        BaseMoveSpeed = _buf.ReadInt();
        PostInit();
    }

    public static RoleData DeserializeRoleData(ByteBuf _buf)
    {
        return new Role.RoleData(_buf);
    }

    /// <summary>
    /// 角色编号
    /// </summary>
    public int Code { get; private set; }
    public Role.RoleType Code_Ref { get; private set; }
    /// <summary>
    /// 等级
    /// </summary>
    public int Level { get; private set; }
    /// <summary>
    /// 血量
    /// </summary>
    public int Hp { get; private set; }
    /// <summary>
    /// 基础攻击力
    /// </summary>
    public int BasePower { get; private set; }
    /// <summary>
    /// 基础移动速度
    /// </summary>
    public int BaseMoveSpeed { get; private set; }

    public const int __ID__ = -2052136008;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        this.Code_Ref = (_tables["Role.TbRole"] as Role.TbRole).GetOrDefault(Code);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Code:" + Code + ","
        + "Level:" + Level + ","
        + "Hp:" + Hp + ","
        + "BasePower:" + BasePower + ","
        + "BaseMoveSpeed:" + BaseMoveSpeed + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
