//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.Role
{
   
public partial class TbRole
{
    private readonly Dictionary<int, Role.RoleType> _dataMap;
    private readonly List<Role.RoleType> _dataList;
    
    public TbRole(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Role.RoleType>();
        _dataList = new List<Role.RoleType>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Role.RoleType _v;
            _v = Role.RoleType.DeserializeRoleType(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Role.RoleType> DataMap => _dataMap;
    public List<Role.RoleType> DataList => _dataList;

    public Role.RoleType GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Role.RoleType Get(int key) => _dataMap[key];
    public Role.RoleType this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}