//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.Role
{
   
public partial class TbRoleData
{
    private readonly List<Role.RoleData> _dataList;

    private Dictionary<(int, int), Role.RoleData> _dataMapUnion;

    public TbRoleData(ByteBuf _buf)
    {
        _dataList = new List<Role.RoleData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Role.RoleData _v;
            _v = Role.RoleData.DeserializeRoleData(_buf);
            _dataList.Add(_v);
        }
        _dataMapUnion = new Dictionary<(int, int), Role.RoleData>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.Level, _v.Code), _v);
        }
        PostInit();
    }


    public List<Role.RoleData> DataList => _dataList;

    public Role.RoleData Get(int level, int code) => _dataMapUnion.TryGetValue((level, code), out Role.RoleData __v) ? __v : null;

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}