//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Monster
{

public sealed partial class MonsterData :  Bright.Config.BeanBase 
{
    public MonsterData(ByteBuf _buf) 
    {
        Code = _buf.ReadInt();
        Level = _buf.ReadInt();
        Hp = _buf.ReadInt();
        BasePower = _buf.ReadInt();
        BaseMoveSpeed = _buf.ReadInt();
        PostInit();
    }

    public static MonsterData DeserializeMonsterData(ByteBuf _buf)
    {
        return new Monster.MonsterData(_buf);
    }

    /// <summary>
    /// 角色编号
    /// </summary>
    public int Code { get; private set; }
    public Monster.MonsterType Code_Ref { get; private set; }
    /// <summary>
    /// 等级
    /// </summary>
    public int Level { get; private set; }
    /// <summary>
    /// 血量
    /// </summary>
    public int Hp { get; private set; }
    /// <summary>
    /// 基础攻击力
    /// </summary>
    public int BasePower { get; private set; }
    /// <summary>
    /// 基础移动速度
    /// </summary>
    public int BaseMoveSpeed { get; private set; }

    public const int __ID__ = 1081714256;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        this.Code_Ref = (_tables["Monster.TbMonster"] as Monster.TbMonster).GetOrDefault(Code);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Code:" + Code + ","
        + "Level:" + Level + ","
        + "Hp:" + Hp + ","
        + "BasePower:" + BasePower + ","
        + "BaseMoveSpeed:" + BaseMoveSpeed + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
