//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.Monster
{

public sealed partial class MonsterType :  Bright.Config.BeanBase 
{
    public MonsterType(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        { if(!_json["type_code"].IsString) { throw new SerializationException(); }  TypeCode = _json["type_code"]; }
        PostInit();
    }

    public MonsterType(int id, string name, string type_code ) 
    {
        this.Id = id;
        this.Name = name;
        this.TypeCode = type_code;
        PostInit();
    }

    public static MonsterType DeserializeMonsterType(JSONNode _json)
    {
        return new Monster.MonsterType(_json);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 角色类型编号
    /// </summary>
    public string TypeCode { get; private set; }

    public const int __ID__ = 1082213856;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "TypeCode:" + TypeCode + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
