//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.Monster
{

public sealed partial class TbMonsterData
{
    private readonly List<Monster.MonsterData> _dataList;
    
    private Dictionary<(int, int), Monster.MonsterData> _dataMapUnion;

    public TbMonsterData(JSONNode _json)
    {
        _dataList = new List<Monster.MonsterData>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = Monster.MonsterData.DeserializeMonsterData(_row);
            _dataList.Add(_v);
        }
        _dataMapUnion = new Dictionary<(int, int), Monster.MonsterData>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.Level, _v.Code), _v);
        }
        PostInit();
    }

    public List<Monster.MonsterData> DataList => _dataList;

    public Monster.MonsterData Get(int level, int code) => _dataMapUnion.TryGetValue((level, code), out Monster.MonsterData __v) ? __v : null;

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }

    
    partial void PostInit();
    partial void PostResolve();
}

}