//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{

public sealed partial class audioData
{
    private readonly Dictionary<int, audio> _dataMap;
    private readonly List<audio> _dataList;
    
    public audioData(JSONNode _json)
    {
        _dataMap = new Dictionary<int, audio>();
        _dataList = new List<audio>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = audio.Deserializeaudio(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, audio> DataMap => _dataMap;
    public List<audio> DataList => _dataList;

    public audio GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public audio Get(int key) => _dataMap[key];
    public audio this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}