//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{

public sealed partial class audio :  Bright.Config.BeanBase 
{
    public audio(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["streaning"].IsString) { throw new SerializationException(); }  Streaning = _json["streaning"]; }
        { if(!_json["assetBuild"].IsString) { throw new SerializationException(); }  AssetBuild = _json["assetBuild"]; }
        PostInit();
    }

    public audio(int id, string streaning, string assetBuild ) 
    {
        this.Id = id;
        this.Streaning = streaning;
        this.AssetBuild = assetBuild;
        PostInit();
    }

    public static audio Deserializeaudio(JSONNode _json)
    {
        return new audio(_json);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 资源路径
    /// </summary>
    public string Streaning { get; private set; }
    /// <summary>
    /// AB包路径
    /// </summary>
    public string AssetBuild { get; private set; }

    public const int __ID__ = 93166550;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Streaning:" + Streaning + ","
        + "AssetBuild:" + AssetBuild + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
