//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{

public sealed partial class role :  Bright.Config.BeanBase 
{
    public role(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["headIcon"].IsString) { throw new SerializationException(); }  HeadIcon = _json["headIcon"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        { if(!_json["bodyIcon"].IsString) { throw new SerializationException(); }  BodyIcon = _json["bodyIcon"]; }
        { if(!_json["info"].IsString) { throw new SerializationException(); }  Info = _json["info"]; }
        PostInit();
    }

    public role(int id, string headIcon, string name, string bodyIcon, string info ) 
    {
        this.Id = id;
        this.HeadIcon = headIcon;
        this.Name = name;
        this.BodyIcon = bodyIcon;
        this.Info = info;
        PostInit();
    }

    public static role Deserializerole(JSONNode _json)
    {
        return new role(_json);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 头像
    /// </summary>
    public string HeadIcon { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 全身像
    /// </summary>
    public string BodyIcon { get; private set; }
    /// <summary>
    /// 角色介绍
    /// </summary>
    public string Info { get; private set; }

    public const int __ID__ = 3506294;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "HeadIcon:" + HeadIcon + ","
        + "Name:" + Name + ","
        + "BodyIcon:" + BodyIcon + ","
        + "Info:" + Info + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
