//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg
{
    /// <summary>
    /// 游戏常量种类
    /// </summary>
    public enum GameConstType
    {
        /// <summary>
        /// 默认角色
        /// </summary>
        DEF_PLAYER = 1,
        /// <summary>
        /// 默认重力
        /// </summary>
        DEF_GRAVITY = 2,
    }
}
