//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;

namespace cfg
{
   
public sealed partial class Tables
{
    public Const.TbGameConst TbGameConst {get; }
    public Role.TbRole TbRole {get; }
    public Role.TbRoleData TbRoleData {get; }
    public Monster.TbMonsterData TbMonsterData {get; }
    public Monster.TbMonster TbMonster {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbGameConst = new Const.TbGameConst(loader("const_tbgameconst")); 
        tables.Add("Const.TbGameConst", TbGameConst);
        TbRole = new Role.TbRole(loader("role_tbrole")); 
        tables.Add("Role.TbRole", TbRole);
        TbRoleData = new Role.TbRoleData(loader("role_tbroledata")); 
        tables.Add("Role.TbRoleData", TbRoleData);
        TbMonsterData = new Monster.TbMonsterData(loader("monster_tbmonsterdata")); 
        tables.Add("Monster.TbMonsterData", TbMonsterData);
        TbMonster = new Monster.TbMonster(loader("monster_tbmonster")); 
        tables.Add("Monster.TbMonster", TbMonster);
        PostInit();

        TbGameConst.Resolve(tables); 
        TbRole.Resolve(tables); 
        TbRoleData.Resolve(tables); 
        TbMonsterData.Resolve(tables); 
        TbMonster.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbGameConst.TranslateText(translator); 
        TbRole.TranslateText(translator); 
        TbRoleData.TranslateText(translator); 
        TbMonsterData.TranslateText(translator); 
        TbMonster.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
