//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;

namespace cfg
{
   
public sealed class Tables
{
    public item.TbItem TbItem {get; }
    public item.TbBox TbBox {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbItem = new item.TbItem(loader("item_tbitem")); 
        tables.Add("item.TbItem", TbItem);
        TbBox = new item.TbBox(loader("item_tbbox")); 
        tables.Add("item.TbBox", TbBox);

        TbItem.Resolve(tables); 
        TbBox.Resolve(tables); 
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbItem.TranslateText(translator); 
        TbBox.TranslateText(translator); 
    }
}

}
