//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.item
{

public sealed class TbBox
{
    private readonly Dictionary<int, item.Box> _dataMap;
    private readonly List<item.Box> _dataList;
    
    public TbBox(JSONNode _json)
    {
        _dataMap = new Dictionary<int, item.Box>();
        _dataList = new List<item.Box>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = item.Box.DeserializeBox(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public Dictionary<int, item.Box> DataMap => _dataMap;
    public List<item.Box> DataList => _dataList;

    public item.Box GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public item.Box Get(int key) => _dataMap[key];
    public item.Box this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
}

}