//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg.Const
{

public sealed partial class GameConst :  Bright.Config.BeanBase 
{
    public GameConst(ByteBuf _buf) 
    {
        DefPlayer = _buf.ReadInt();
        DefGravity = _buf.ReadUnityVector2();
        PostInit();
    }

    public static GameConst DeserializeGameConst(ByteBuf _buf)
    {
        return new Const.GameConst(_buf);
    }

    public int DefPlayer { get; private set; }
    public UnityEngine.Vector2 DefGravity { get; private set; }

    public const int __ID__ = 1930847622;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "DefPlayer:" + DefPlayer + ","
        + "DefGravity:" + DefGravity + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
