// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AchievementDefine.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtoCmd {

  /// <summary>Holder for reflection information generated from AchievementDefine.proto</summary>
  public static partial class AchievementDefineReflection {

    #region Descriptor
    /// <summary>File descriptor for AchievementDefine.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AchievementDefineReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdBY2hpZXZlbWVudERlZmluZS5wcm90bxIIUHJvdG9DbWQqwAYKD0FjaGll",
            "dmVtZW50VHlwZRIYChRBY2hpZXZlbWVudFR5cGVfTm9uZRAAEhYKEkFjaGll",
            "dmVtZW50VHlwZV9GQhABEhoKFkFjaGlldmVtZW50VHlwZV9GQkJPU1MQAhIf",
            "ChtBY2hpZXZlbWVudFR5cGVfS2lsbE1vbnN0ZXIQAxIYChRBY2hpZXZlbWVu",
            "dFR5cGVfU3RhchAEEh4KGkFjaGlldmVtZW50VHlwZV9TdHJlbmd0aGVuEAUS",
            "IAocQWNoaWV2ZW1lbnRUeXBlX0FyZW5hQ3JlZGl0cxAGEhoKFkFjaGlldmVt",
            "ZW50VHlwZV9TcHJpdGUQBxIaChZBY2hpZXZlbWVudFR5cGVfRnJpZW5kEAgS",
            "GQoVQWNoaWV2ZW1lbnRUeXBlX0xldmVsEAkSHgoaQWNoaWV2ZW1lbnRUeXBl",
            "X0RlYXRoVG93ZXIQChIdChlBY2hpZXZlbWVudFR5cGVfV29ybGRCb3NzEAsS",
            "GQoVQWNoaWV2ZW1lbnRUeXBlX0ZpZ2h0EAwSHgoaQWNoaWV2ZW1lbnRUeXBl",
            "X0FjdGl2aXR5RkIQDRIgChxBY2hpZXZlbWVudFR5cGVfRXF1aXBRdWFsaXR5",
            "EA4SHAoYQWNoaWV2ZW1lbnRUeXBlX0dlbXN0b25lEA8SGAoUQWNoaWV2ZW1l",
            "bnRUeXBlX1J1bmUQEBIcChhBY2hpZXZlbWVudFR5cGVfUnVuZUxpbmsQERIc",
            "ChhBY2hpZXZlbWVudFR5cGVfQXJlbmFXaW4QEhIdChlBY2hpZXZlbWVudFR5",
            "cGVfV2luU3RyZWFrEBMSHgoaQWNoaWV2ZW1lbnRUeXBlX0xvc2VTdHJlYWsQ",
            "FBIcChhBY2hpZXZlbWVudFR5cGVfU2tpbGxOdW0QFRIYChRBY2hpZXZlbWVu",
            "dFR5cGVfV2luZxAWEiMKH0FjaGlldmVtZW50VHlwZV9TcHJlYWRFZGdlQ291",
            "bnQQFxIjCh9BY2hpZXZlbWVudFR5cGVfT3JhbmdlRWRnZUNvdW50EBgSHwob",
            "QWNoaWV2ZW1lbnRUeXBlX0JhdHRsZUZpbGVkEBkSHQoZQWNoaWV2ZW1lbnRU",
            "eXBlX0pvaW5HdWlsZBAaKm8KEUFjaGlldmVtZW50U3RhdHVzEh8KG0FjaGll",
            "dmVtZW50U3RhdHVzX05vdEFjdGl2ZRAAEhwKGEFjaGlldmVtZW50U3RhdHVz",
            "X0FjdGl2ZRABEhsKF0FjaGlldmVtZW50U3RhdHVzX1Rha2VuEAIquwEKFUFj",
            "aGlldmVtZW50UmV3YXJkVHlwZRIeChpBY2hpZXZlbWVudFJld2FyZFR5cGVf",
            "Tm9uZRAAEh8KG0FjaGlldmVtZW50UmV3YXJkVHlwZV9Nb25leRABEiEKHUFj",
            "aGlldmVtZW50UmV3YXJkVHlwZV9EaWFtb25kEAISHwobQWNoaWV2ZW1lbnRS",
            "ZXdhcmRUeXBlX0hvbm9yEAMSHQoZQWNoaWV2ZW1lbnRSZXdhcmRUeXBlX1Bl",
            "dBAG"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ProtoCmd.AchievementType), typeof(global::ProtoCmd.AchievementStatus), typeof(global::ProtoCmd.AchievementRewardType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// �ɾ�����
  /// </summary>
  public enum AchievementType {
    /// <summary>
    /// ��
    /// </summary>
    [pbr::OriginalName("AchievementType_None")] None = 0,
    /// <summary>
    /// ��ͨ����
    /// </summary>
    [pbr::OriginalName("AchievementType_FB")] Fb = 1,
    /// <summary>
    /// ����BOSS
    /// </summary>
    [pbr::OriginalName("AchievementType_FBBOSS")] Fbboss = 2,
    /// <summary>
    /// ɱ������
    /// </summary>
    [pbr::OriginalName("AchievementType_KillMonster")] KillMonster = 3,
    /// <summary>
    /// �ؿ��Ǽ�
    /// </summary>
    [pbr::OriginalName("AchievementType_Star")] Star = 4,
    /// <summary>
    /// װ��ǿ��
    /// </summary>
    [pbr::OriginalName("AchievementType_Strengthen")] Strengthen = 5,
    /// <summary>
    /// ����������
    /// </summary>
    [pbr::OriginalName("AchievementType_ArenaCredits")] ArenaCredits = 6,
    /// <summary>
    /// �ػ�����
    /// </summary>
    [pbr::OriginalName("AchievementType_Sprite")] Sprite = 7,
    /// <summary>
    /// ����
    /// </summary>
    [pbr::OriginalName("AchievementType_Friend")] Friend = 8,
    /// <summary>
    /// ����ȼ�
    /// </summary>
    [pbr::OriginalName("AchievementType_Level")] Level = 9,
    /// <summary>
    /// ������
    /// </summary>
    [pbr::OriginalName("AchievementType_DeathTower")] DeathTower = 10,
    /// <summary>
    /// ����BOSS
    /// </summary>
    [pbr::OriginalName("AchievementType_WorldBoss")] WorldBoss = 11,
    /// <summary>
    /// ս����
    /// </summary>
    [pbr::OriginalName("AchievementType_Fight")] Fight = 12,
    /// <summary>
    /// �FB
    /// </summary>
    [pbr::OriginalName("AchievementType_ActivityFB")] ActivityFb = 13,
    /// <summary>
    /// װ��Ʒ��
    /// </summary>
    [pbr::OriginalName("AchievementType_EquipQuality")] EquipQuality = 14,
    /// <summary>
    /// ��ʯ
    /// </summary>
    [pbr::OriginalName("AchievementType_Gemstone")] Gemstone = 15,
    /// <summary>
    /// ����
    /// </summary>
    [pbr::OriginalName("AchievementType_Rune")] Rune = 16,
    /// <summary>
    /// ���Ĺ���
    /// </summary>
    [pbr::OriginalName("AchievementType_RuneLink")] RuneLink = 17,
    /// <summary>
    /// �������ۻ�ʤ��
    /// </summary>
    [pbr::OriginalName("AchievementType_ArenaWin")] ArenaWin = 18,
    /// <summary>
    /// ��������ʤ
    /// </summary>
    [pbr::OriginalName("AchievementType_WinStreak")] WinStreak = 19,
    /// <summary>
    /// ����������
    /// </summary>
    [pbr::OriginalName("AchievementType_LoseStreak")] LoseStreak = 20,
    /// <summary>
    /// ��������
    /// </summary>
    [pbr::OriginalName("AchievementType_SkillNum")] SkillNum = 21,
    /// <summary>
    /// ��ó��
    /// </summary>
    [pbr::OriginalName("AchievementType_Wing")] Wing = 22,
    /// <summary>
    /// �Ա߸���
    /// </summary>
    [pbr::OriginalName("AchievementType_SpreadEdgeCount")] SpreadEdgeCount = 23,
    /// <summary>
    /// �ȱ�����
    /// </summary>
    [pbr::OriginalName("AchievementType_OrangeEdgeCount")] OrangeEdgeCount = 24,
    /// <summary>
    /// ս���ۼ�ʤ������
    /// </summary>
    [pbr::OriginalName("AchievementType_BattleFiled")] BattleFiled = 25,
    /// <summary>
    /// �������
    /// </summary>
    [pbr::OriginalName("AchievementType_JoinGuild")] JoinGuild = 26,
  }

  /// <summary>
  /// �ɾ�״̬
  /// </summary>
  public enum AchievementStatus {
    /// <summary>
    /// ��δ��������������ȡ
    /// </summary>
    [pbr::OriginalName("AchievementStatus_NotActive")] NotActive = 0,
    /// <summary>
    /// ����ȡ
    /// </summary>
    [pbr::OriginalName("AchievementStatus_Active")] Active = 1,
    /// <summary>
    /// ����ȡ
    /// </summary>
    [pbr::OriginalName("AchievementStatus_Taken")] Taken = 2,
  }

  /// <summary>
  /// �ɾͽ�������
  /// </summary>
  public enum AchievementRewardType {
    /// <summary>
    /// ��
    /// </summary>
    [pbr::OriginalName("AchievementRewardType_None")] None = 0,
    /// <summary>
    /// ���
    /// </summary>
    [pbr::OriginalName("AchievementRewardType_Money")] Money = 1,
    /// <summary>
    /// ��ʯ
    /// </summary>
    [pbr::OriginalName("AchievementRewardType_Diamond")] Diamond = 2,
    /// <summary>
    /// ������
    /// </summary>
    [pbr::OriginalName("AchievementRewardType_Honor")] Honor = 3,
    /// <summary>
    /// ����
    /// </summary>
    [pbr::OriginalName("AchievementRewardType_Pet")] Pet = 6,
  }

  #endregion

}

#endregion Designer generated code
