// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ab.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ab.proto</summary>
public static partial class AbReflection {

  #region Descriptor
  /// <summary>File descriptor for ab.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static AbReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CghhYi5wcm90byI1CghBQkNvbmZpZxIOCgZBQk5hbWUYASACKAkSDAoEU2l6",
          "ZRgCIAIoBRILCgNDUkMYAyACKAk="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ABConfig), global::ABConfig.Parser, new[]{ "ABName", "Size", "CRC" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ABConfig : pb::IMessage<ABConfig>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ABConfig> _parser = new pb::MessageParser<ABConfig>(() => new ABConfig());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ABConfig> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AbReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ABConfig() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ABConfig(ABConfig other) : this() {
    _hasBits0 = other._hasBits0;
    aBName_ = other.aBName_;
    size_ = other.size_;
    cRC_ = other.cRC_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ABConfig Clone() {
    return new ABConfig(this);
  }

  /// <summary>Field number for the "ABName" field.</summary>
  public const int ABNameFieldNumber = 1;
  private readonly static string ABNameDefaultValue = "";

  private string aBName_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ABName {
    get { return aBName_ ?? ABNameDefaultValue; }
    set {
      aBName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "ABName" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasABName {
    get { return aBName_ != null; }
  }
  /// <summary>Clears the value of the "ABName" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearABName() {
    aBName_ = null;
  }

  /// <summary>Field number for the "Size" field.</summary>
  public const int SizeFieldNumber = 2;
  private readonly static int SizeDefaultValue = 0;

  private int size_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Size {
    get { if ((_hasBits0 & 1) != 0) { return size_; } else { return SizeDefaultValue; } }
    set {
      _hasBits0 |= 1;
      size_ = value;
    }
  }
  /// <summary>Gets whether the "Size" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasSize {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "Size" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearSize() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "CRC" field.</summary>
  public const int CRCFieldNumber = 3;
  private readonly static string CRCDefaultValue = "";

  private string cRC_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CRC {
    get { return cRC_ ?? CRCDefaultValue; }
    set {
      cRC_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "CRC" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasCRC {
    get { return cRC_ != null; }
  }
  /// <summary>Clears the value of the "CRC" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearCRC() {
    cRC_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ABConfig);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ABConfig other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ABName != other.ABName) return false;
    if (Size != other.Size) return false;
    if (CRC != other.CRC) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasABName) hash ^= ABName.GetHashCode();
    if (HasSize) hash ^= Size.GetHashCode();
    if (HasCRC) hash ^= CRC.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasABName) {
      output.WriteRawTag(10);
      output.WriteString(ABName);
    }
    if (HasSize) {
      output.WriteRawTag(16);
      output.WriteInt32(Size);
    }
    if (HasCRC) {
      output.WriteRawTag(26);
      output.WriteString(CRC);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasABName) {
      output.WriteRawTag(10);
      output.WriteString(ABName);
    }
    if (HasSize) {
      output.WriteRawTag(16);
      output.WriteInt32(Size);
    }
    if (HasCRC) {
      output.WriteRawTag(26);
      output.WriteString(CRC);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasABName) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ABName);
    }
    if (HasSize) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Size);
    }
    if (HasCRC) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CRC);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ABConfig other) {
    if (other == null) {
      return;
    }
    if (other.HasABName) {
      ABName = other.ABName;
    }
    if (other.HasSize) {
      Size = other.Size;
    }
    if (other.HasCRC) {
      CRC = other.CRC;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          ABName = input.ReadString();
          break;
        }
        case 16: {
          Size = input.ReadInt32();
          break;
        }
        case 26: {
          CRC = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          ABName = input.ReadString();
          break;
        }
        case 16: {
          Size = input.ReadInt32();
          break;
        }
        case 26: {
          CRC = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
