// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BubbleDefine.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtoCmd {

  /// <summary>Holder for reflection information generated from BubbleDefine.proto</summary>
  public static partial class BubbleDefineReflection {

    #region Descriptor
    /// <summary>File descriptor for BubbleDefine.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BubbleDefineReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJCdWJibGVEZWZpbmUucHJvdG8SCFByb3RvQ21kKsADChlOZXdCaWVHdWlk",
            "ZUVsZW1lbnRTdWJ0eXBlEhEKBE5vbmUQ////////////ARIUCg9EZWJsb2Nr",
            "aW5nTGV2ZWwQ6wcSFQoQRGVibG9ja2luZ0NvdXJzZRDpBxIVChBEZWJsb2Nr",
            "aW5nU2FmYXJpEO4HEhcKEkFjY29tcGxpc2hHdWlkYW5jZRDvBxIMCgdHZXRS",
            "b2xlEPEuEhQKD1JvbGVLaWxsTW9uc3RlchDiDxIYChNXYWxsU2FmYXJpRmlu",
            "aXNoTnVtENEPEhIKDVJvbGVPbndDb21iYXQQ0A8SFgoRUGFzc1N0b3J5SW5z",
            "dGFuY2UQ1g8SFAoPUGFzc01hcEluc3RhbmNlENcPEhAKC0ZpcnN0Q29tYmF0",
            "EOYPEhAKC0NvbWJhdFN0YXRlEMQTEhIKDUVudHJhbmNlU2NlbmUQoR8SDwoK",
            "RW50cmFuY2VVSRCiHxIRCgxSb2xlRXhwTGV2ZWwQ9S4SFAoPUm9sZUV4cExl",
            "dmVsTWF4EPYuEg8KCkV4dHJhY3ROdW0Q2jYSEgoNRmluaXNoTG90dGVyeRDb",
            "NhIOCglGaXJzdFNpZ24Q3zYSDAoHU2lnbk51bRD8Lg=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ProtoCmd.NewBieGuideElementSubtype), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 新手引导条件类型（用在SysCondition表中）
  /// </summary>
  public enum NewBieGuideElementSubtype {
    /// <summary>
    /// 无
    /// </summary>
    [pbr::OriginalName("None")] None = -1,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("DeblockingLevel")] DeblockingLevel = 1003,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("DeblockingCourse")] DeblockingCourse = 1001,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("DeblockingSafari")] DeblockingSafari = 1006,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("AccomplishGuidance")] AccomplishGuidance = 1007,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("GetRole")] GetRole = 6001,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("RoleKillMonster")] RoleKillMonster = 2018,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("WallSafariFinishNum")] WallSafariFinishNum = 2001,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("RoleOnwCombat")] RoleOnwCombat = 2000,
    /// <summary>
    ///通过故事关卡  参数1=StoryInstance表的StoryInstanceID
    /// </summary>
    [pbr::OriginalName("PassStoryInstance")] PassStoryInstance = 2006,
    /// <summary>
    ///通过日常关卡  参数1=难度[0/1/2/3...]  参数2=MapInstance表的InstanceID
    /// </summary>
    [pbr::OriginalName("PassMapInstance")] PassMapInstance = 2007,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("FirstCombat")] FirstCombat = 2022,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("CombatState")] CombatState = 2500,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("EntranceScene")] EntranceScene = 4001,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("EntranceUI")] EntranceUi = 4002,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("RoleExpLevel")] RoleExpLevel = 6005,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("RoleExpLevelMax")] RoleExpLevelMax = 6006,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("ExtractNum")] ExtractNum = 7002,
    /// <summary>
    /// 抽卡完成
    /// </summary>
    [pbr::OriginalName("FinishLottery")] FinishLottery = 7003,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("FirstSign")] FirstSign = 7007,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("SignNum")] SignNum = 6012,
  }

  #endregion

}

#endregion Designer generated code
