// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: test_battle.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Battle {

  /// <summary>Holder for reflection information generated from test_battle.proto</summary>
  public static partial class TestBattleReflection {

    #region Descriptor
    /// <summary>File descriptor for test_battle.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TestBattleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChF0ZXN0X2JhdHRsZS5wcm90bxIGYmF0dGxlIkAKB29uZV9jbWQSEQoGY21k",
            "X2lkGAEgASgFOgEwEg4KA1VJRBgCIAEoDToBMBISCghjbWRfZGF0YRgDIAEo",
            "DDoAIvoCChVudGZfYmF0dGxlX2ZyYW1lX2RhdGESDwoEdGltZRgBIAEoBToB",
            "MBI5CglzbG90X2xpc3QYAyADKAsyJi5iYXR0bGUubnRmX2JhdHRsZV9mcmFt",
            "ZV9kYXRhLm9uZV9zbG90EhsKEHNlcnZlcl9mcm9tX3Nsb3QYBSABKAU6ATAS",
            "GQoOc2VydmVyX3RvX3Nsb3QYBiABKAU6ATASHAoRc2VydmVyX2N1cnJfZnJh",
            "bWUYByABKAU6ATASGQoOaXNfY2hlY2tfZnJhbWUYCCABKAU6ATAaRwoOY21k",
            "X3dpdGhfZnJhbWUSFwoMc2VydmVyX2ZyYW1lGAEgASgFOgEwEhwKA2NtZBgC",
            "IAEoCzIPLmJhdHRsZS5vbmVfY21kGlsKCG9uZV9zbG90Eg8KBHNsb3QYASAB",
            "KAU6ATASPgoIY21kX2xpc3QYAyADKAsyLC5iYXR0bGUubnRmX2JhdHRsZV9m",
            "cmFtZV9kYXRhLmNtZF93aXRoX2ZyYW1l"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Battle.one_cmd), global::Battle.one_cmd.Parser, new[]{ "CmdId", "UID", "CmdData" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Battle.ntf_battle_frame_data), global::Battle.ntf_battle_frame_data.Parser, new[]{ "Time", "SlotList", "ServerFromSlot", "ServerToSlot", "ServerCurrFrame", "IsCheckFrame" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Battle.ntf_battle_frame_data.Types.cmd_with_frame), global::Battle.ntf_battle_frame_data.Types.cmd_with_frame.Parser, new[]{ "ServerFrame", "Cmd" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Battle.ntf_battle_frame_data.Types.one_slot), global::Battle.ntf_battle_frame_data.Types.one_slot.Parser, new[]{ "Slot", "CmdList" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class one_cmd : pb::IMessage<one_cmd>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<one_cmd> _parser = new pb::MessageParser<one_cmd>(() => new one_cmd());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<one_cmd> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Battle.TestBattleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public one_cmd() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public one_cmd(one_cmd other) : this() {
      _hasBits0 = other._hasBits0;
      cmdId_ = other.cmdId_;
      uID_ = other.uID_;
      cmdData_ = other.cmdData_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public one_cmd Clone() {
      return new one_cmd(this);
    }

    /// <summary>Field number for the "cmd_id" field.</summary>
    public const int CmdIdFieldNumber = 1;
    private readonly static int CmdIdDefaultValue = 0;

    private int cmdId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CmdId {
      get { if ((_hasBits0 & 1) != 0) { return cmdId_; } else { return CmdIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        cmdId_ = value;
      }
    }
    /// <summary>Gets whether the "cmd_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCmdId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "cmd_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCmdId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "UID" field.</summary>
    public const int UIDFieldNumber = 2;
    private readonly static uint UIDDefaultValue = 0;

    private uint uID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint UID {
      get { if ((_hasBits0 & 2) != 0) { return uID_; } else { return UIDDefaultValue; } }
      set {
        _hasBits0 |= 2;
        uID_ = value;
      }
    }
    /// <summary>Gets whether the "UID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUID {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "UID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUID() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "cmd_data" field.</summary>
    public const int CmdDataFieldNumber = 3;
    private readonly static pb::ByteString CmdDataDefaultValue = pb::ByteString.Empty;

    private pb::ByteString cmdData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString CmdData {
      get { return cmdData_ ?? CmdDataDefaultValue; }
      set {
        cmdData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "cmd_data" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCmdData {
      get { return cmdData_ != null; }
    }
    /// <summary>Clears the value of the "cmd_data" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCmdData() {
      cmdData_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as one_cmd);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(one_cmd other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CmdId != other.CmdId) return false;
      if (UID != other.UID) return false;
      if (CmdData != other.CmdData) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasCmdId) hash ^= CmdId.GetHashCode();
      if (HasUID) hash ^= UID.GetHashCode();
      if (HasCmdData) hash ^= CmdData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasCmdId) {
        output.WriteRawTag(8);
        output.WriteInt32(CmdId);
      }
      if (HasUID) {
        output.WriteRawTag(16);
        output.WriteUInt32(UID);
      }
      if (HasCmdData) {
        output.WriteRawTag(26);
        output.WriteBytes(CmdData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasCmdId) {
        output.WriteRawTag(8);
        output.WriteInt32(CmdId);
      }
      if (HasUID) {
        output.WriteRawTag(16);
        output.WriteUInt32(UID);
      }
      if (HasCmdData) {
        output.WriteRawTag(26);
        output.WriteBytes(CmdData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasCmdId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CmdId);
      }
      if (HasUID) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UID);
      }
      if (HasCmdData) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(CmdData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(one_cmd other) {
      if (other == null) {
        return;
      }
      if (other.HasCmdId) {
        CmdId = other.CmdId;
      }
      if (other.HasUID) {
        UID = other.UID;
      }
      if (other.HasCmdData) {
        CmdData = other.CmdData;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CmdId = input.ReadInt32();
            break;
          }
          case 16: {
            UID = input.ReadUInt32();
            break;
          }
          case 26: {
            CmdData = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CmdId = input.ReadInt32();
            break;
          }
          case 16: {
            UID = input.ReadUInt32();
            break;
          }
          case 26: {
            CmdData = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ntf_battle_frame_data : pb::IMessage<ntf_battle_frame_data>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ntf_battle_frame_data> _parser = new pb::MessageParser<ntf_battle_frame_data>(() => new ntf_battle_frame_data());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ntf_battle_frame_data> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Battle.TestBattleReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ntf_battle_frame_data() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ntf_battle_frame_data(ntf_battle_frame_data other) : this() {
      _hasBits0 = other._hasBits0;
      time_ = other.time_;
      slotList_ = other.slotList_.Clone();
      serverFromSlot_ = other.serverFromSlot_;
      serverToSlot_ = other.serverToSlot_;
      serverCurrFrame_ = other.serverCurrFrame_;
      isCheckFrame_ = other.isCheckFrame_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ntf_battle_frame_data Clone() {
      return new ntf_battle_frame_data(this);
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 1;
    private readonly static int TimeDefaultValue = 0;

    private int time_;
    /// <summary>
    /// 这一帧的时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Time {
      get { if ((_hasBits0 & 1) != 0) { return time_; } else { return TimeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        time_ = value;
      }
    }
    /// <summary>Gets whether the "time" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTime {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "time" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTime() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "slot_list" field.</summary>
    public const int SlotListFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Battle.ntf_battle_frame_data.Types.one_slot> _repeated_slotList_codec
        = pb::FieldCodec.ForMessage(26, global::Battle.ntf_battle_frame_data.Types.one_slot.Parser);
    private readonly pbc::RepeatedField<global::Battle.ntf_battle_frame_data.Types.one_slot> slotList_ = new pbc::RepeatedField<global::Battle.ntf_battle_frame_data.Types.one_slot>();
    /// <summary>
    /// slot列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Battle.ntf_battle_frame_data.Types.one_slot> SlotList {
      get { return slotList_; }
    }

    /// <summary>Field number for the "server_from_slot" field.</summary>
    public const int ServerFromSlotFieldNumber = 5;
    private readonly static int ServerFromSlotDefaultValue = 0;

    private int serverFromSlot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ServerFromSlot {
      get { if ((_hasBits0 & 2) != 0) { return serverFromSlot_; } else { return ServerFromSlotDefaultValue; } }
      set {
        _hasBits0 |= 2;
        serverFromSlot_ = value;
      }
    }
    /// <summary>Gets whether the "server_from_slot" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasServerFromSlot {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "server_from_slot" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearServerFromSlot() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "server_to_slot" field.</summary>
    public const int ServerToSlotFieldNumber = 6;
    private readonly static int ServerToSlotDefaultValue = 0;

    private int serverToSlot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ServerToSlot {
      get { if ((_hasBits0 & 4) != 0) { return serverToSlot_; } else { return ServerToSlotDefaultValue; } }
      set {
        _hasBits0 |= 4;
        serverToSlot_ = value;
      }
    }
    /// <summary>Gets whether the "server_to_slot" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasServerToSlot {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "server_to_slot" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearServerToSlot() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "server_curr_frame" field.</summary>
    public const int ServerCurrFrameFieldNumber = 7;
    private readonly static int ServerCurrFrameDefaultValue = 0;

    private int serverCurrFrame_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ServerCurrFrame {
      get { if ((_hasBits0 & 8) != 0) { return serverCurrFrame_; } else { return ServerCurrFrameDefaultValue; } }
      set {
        _hasBits0 |= 8;
        serverCurrFrame_ = value;
      }
    }
    /// <summary>Gets whether the "server_curr_frame" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasServerCurrFrame {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "server_curr_frame" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearServerCurrFrame() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "is_check_frame" field.</summary>
    public const int IsCheckFrameFieldNumber = 8;
    private readonly static int IsCheckFrameDefaultValue = 0;

    private int isCheckFrame_;
    /// <summary>
    /// 1 表示这帧需要检测
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IsCheckFrame {
      get { if ((_hasBits0 & 16) != 0) { return isCheckFrame_; } else { return IsCheckFrameDefaultValue; } }
      set {
        _hasBits0 |= 16;
        isCheckFrame_ = value;
      }
    }
    /// <summary>Gets whether the "is_check_frame" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIsCheckFrame {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "is_check_frame" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIsCheckFrame() {
      _hasBits0 &= ~16;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ntf_battle_frame_data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ntf_battle_frame_data other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Time != other.Time) return false;
      if(!slotList_.Equals(other.slotList_)) return false;
      if (ServerFromSlot != other.ServerFromSlot) return false;
      if (ServerToSlot != other.ServerToSlot) return false;
      if (ServerCurrFrame != other.ServerCurrFrame) return false;
      if (IsCheckFrame != other.IsCheckFrame) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasTime) hash ^= Time.GetHashCode();
      hash ^= slotList_.GetHashCode();
      if (HasServerFromSlot) hash ^= ServerFromSlot.GetHashCode();
      if (HasServerToSlot) hash ^= ServerToSlot.GetHashCode();
      if (HasServerCurrFrame) hash ^= ServerCurrFrame.GetHashCode();
      if (HasIsCheckFrame) hash ^= IsCheckFrame.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasTime) {
        output.WriteRawTag(8);
        output.WriteInt32(Time);
      }
      slotList_.WriteTo(output, _repeated_slotList_codec);
      if (HasServerFromSlot) {
        output.WriteRawTag(40);
        output.WriteInt32(ServerFromSlot);
      }
      if (HasServerToSlot) {
        output.WriteRawTag(48);
        output.WriteInt32(ServerToSlot);
      }
      if (HasServerCurrFrame) {
        output.WriteRawTag(56);
        output.WriteInt32(ServerCurrFrame);
      }
      if (HasIsCheckFrame) {
        output.WriteRawTag(64);
        output.WriteInt32(IsCheckFrame);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasTime) {
        output.WriteRawTag(8);
        output.WriteInt32(Time);
      }
      slotList_.WriteTo(ref output, _repeated_slotList_codec);
      if (HasServerFromSlot) {
        output.WriteRawTag(40);
        output.WriteInt32(ServerFromSlot);
      }
      if (HasServerToSlot) {
        output.WriteRawTag(48);
        output.WriteInt32(ServerToSlot);
      }
      if (HasServerCurrFrame) {
        output.WriteRawTag(56);
        output.WriteInt32(ServerCurrFrame);
      }
      if (HasIsCheckFrame) {
        output.WriteRawTag(64);
        output.WriteInt32(IsCheckFrame);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasTime) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Time);
      }
      size += slotList_.CalculateSize(_repeated_slotList_codec);
      if (HasServerFromSlot) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ServerFromSlot);
      }
      if (HasServerToSlot) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ServerToSlot);
      }
      if (HasServerCurrFrame) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ServerCurrFrame);
      }
      if (HasIsCheckFrame) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IsCheckFrame);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ntf_battle_frame_data other) {
      if (other == null) {
        return;
      }
      if (other.HasTime) {
        Time = other.Time;
      }
      slotList_.Add(other.slotList_);
      if (other.HasServerFromSlot) {
        ServerFromSlot = other.ServerFromSlot;
      }
      if (other.HasServerToSlot) {
        ServerToSlot = other.ServerToSlot;
      }
      if (other.HasServerCurrFrame) {
        ServerCurrFrame = other.ServerCurrFrame;
      }
      if (other.HasIsCheckFrame) {
        IsCheckFrame = other.IsCheckFrame;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Time = input.ReadInt32();
            break;
          }
          case 26: {
            slotList_.AddEntriesFrom(input, _repeated_slotList_codec);
            break;
          }
          case 40: {
            ServerFromSlot = input.ReadInt32();
            break;
          }
          case 48: {
            ServerToSlot = input.ReadInt32();
            break;
          }
          case 56: {
            ServerCurrFrame = input.ReadInt32();
            break;
          }
          case 64: {
            IsCheckFrame = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Time = input.ReadInt32();
            break;
          }
          case 26: {
            slotList_.AddEntriesFrom(ref input, _repeated_slotList_codec);
            break;
          }
          case 40: {
            ServerFromSlot = input.ReadInt32();
            break;
          }
          case 48: {
            ServerToSlot = input.ReadInt32();
            break;
          }
          case 56: {
            ServerCurrFrame = input.ReadInt32();
            break;
          }
          case 64: {
            IsCheckFrame = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ntf_battle_frame_data message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class cmd_with_frame : pb::IMessage<cmd_with_frame>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<cmd_with_frame> _parser = new pb::MessageParser<cmd_with_frame>(() => new cmd_with_frame());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<cmd_with_frame> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Battle.ntf_battle_frame_data.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public cmd_with_frame() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public cmd_with_frame(cmd_with_frame other) : this() {
          _hasBits0 = other._hasBits0;
          serverFrame_ = other.serverFrame_;
          cmd_ = other.cmd_ != null ? other.cmd_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public cmd_with_frame Clone() {
          return new cmd_with_frame(this);
        }

        /// <summary>Field number for the "server_frame" field.</summary>
        public const int ServerFrameFieldNumber = 1;
        private readonly static int ServerFrameDefaultValue = 0;

        private int serverFrame_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int ServerFrame {
          get { if ((_hasBits0 & 1) != 0) { return serverFrame_; } else { return ServerFrameDefaultValue; } }
          set {
            _hasBits0 |= 1;
            serverFrame_ = value;
          }
        }
        /// <summary>Gets whether the "server_frame" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasServerFrame {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "server_frame" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearServerFrame() {
          _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "cmd" field.</summary>
        public const int CmdFieldNumber = 2;
        private global::Battle.one_cmd cmd_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Battle.one_cmd Cmd {
          get { return cmd_; }
          set {
            cmd_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as cmd_with_frame);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(cmd_with_frame other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (ServerFrame != other.ServerFrame) return false;
          if (!object.Equals(Cmd, other.Cmd)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasServerFrame) hash ^= ServerFrame.GetHashCode();
          if (cmd_ != null) hash ^= Cmd.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasServerFrame) {
            output.WriteRawTag(8);
            output.WriteInt32(ServerFrame);
          }
          if (cmd_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Cmd);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasServerFrame) {
            output.WriteRawTag(8);
            output.WriteInt32(ServerFrame);
          }
          if (cmd_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Cmd);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasServerFrame) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(ServerFrame);
          }
          if (cmd_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Cmd);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(cmd_with_frame other) {
          if (other == null) {
            return;
          }
          if (other.HasServerFrame) {
            ServerFrame = other.ServerFrame;
          }
          if (other.cmd_ != null) {
            if (cmd_ == null) {
              Cmd = new global::Battle.one_cmd();
            }
            Cmd.MergeFrom(other.Cmd);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                ServerFrame = input.ReadInt32();
                break;
              }
              case 18: {
                if (cmd_ == null) {
                  Cmd = new global::Battle.one_cmd();
                }
                input.ReadMessage(Cmd);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                ServerFrame = input.ReadInt32();
                break;
              }
              case 18: {
                if (cmd_ == null) {
                  Cmd = new global::Battle.one_cmd();
                }
                input.ReadMessage(Cmd);
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class one_slot : pb::IMessage<one_slot>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<one_slot> _parser = new pb::MessageParser<one_slot>(() => new one_slot());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<one_slot> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Battle.ntf_battle_frame_data.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public one_slot() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public one_slot(one_slot other) : this() {
          _hasBits0 = other._hasBits0;
          slot_ = other.slot_;
          cmdList_ = other.cmdList_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public one_slot Clone() {
          return new one_slot(this);
        }

        /// <summary>Field number for the "slot" field.</summary>
        public const int SlotFieldNumber = 1;
        private readonly static int SlotDefaultValue = 0;

        private int slot_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Slot {
          get { if ((_hasBits0 & 1) != 0) { return slot_; } else { return SlotDefaultValue; } }
          set {
            _hasBits0 |= 1;
            slot_ = value;
          }
        }
        /// <summary>Gets whether the "slot" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasSlot {
          get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "slot" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearSlot() {
          _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "cmd_list" field.</summary>
        public const int CmdListFieldNumber = 3;
        private static readonly pb::FieldCodec<global::Battle.ntf_battle_frame_data.Types.cmd_with_frame> _repeated_cmdList_codec
            = pb::FieldCodec.ForMessage(26, global::Battle.ntf_battle_frame_data.Types.cmd_with_frame.Parser);
        private readonly pbc::RepeatedField<global::Battle.ntf_battle_frame_data.Types.cmd_with_frame> cmdList_ = new pbc::RepeatedField<global::Battle.ntf_battle_frame_data.Types.cmd_with_frame>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<global::Battle.ntf_battle_frame_data.Types.cmd_with_frame> CmdList {
          get { return cmdList_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as one_slot);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(one_slot other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Slot != other.Slot) return false;
          if(!cmdList_.Equals(other.cmdList_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (HasSlot) hash ^= Slot.GetHashCode();
          hash ^= cmdList_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (HasSlot) {
            output.WriteRawTag(8);
            output.WriteInt32(Slot);
          }
          cmdList_.WriteTo(output, _repeated_cmdList_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (HasSlot) {
            output.WriteRawTag(8);
            output.WriteInt32(Slot);
          }
          cmdList_.WriteTo(ref output, _repeated_cmdList_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (HasSlot) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Slot);
          }
          size += cmdList_.CalculateSize(_repeated_cmdList_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(one_slot other) {
          if (other == null) {
            return;
          }
          if (other.HasSlot) {
            Slot = other.Slot;
          }
          cmdList_.Add(other.cmdList_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Slot = input.ReadInt32();
                break;
              }
              case 26: {
                cmdList_.AddEntriesFrom(input, _repeated_cmdList_codec);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                Slot = input.ReadInt32();
                break;
              }
              case 26: {
                cmdList_.AddEntriesFrom(ref input, _repeated_cmdList_codec);
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
