//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ab.proto
namespace ab
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ABConfig")]
  public partial class ABConfig : global::ProtoBuf.IExtensible
  {
    public ABConfig() {}
    
    private string _ABName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ABName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ABName
    {
      get { return _ABName; }
      set { _ABName = value; }
    }
    private int _Size;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Size
    {
      get { return _Size; }
      set { _Size = value; }
    }
    private string _CRC;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"CRC", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string CRC
    {
      get { return _CRC; }
      set { _CRC = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}