// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ab.proto

#pragma warning disable CS1591, CS0612, CS3021

[System.Serializable]
[global::ProtoBuf.ProtoContract()]
public partial class ABConfig
{
    [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
    public string ABName;

    [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
    public int Size;

    [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
    public string CRC;

}

#pragma warning restore CS1591, CS0612, CS3021
